/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

import opaTest from "sap/ui/test/opaQunit";
import type { Given, When, Then } from "./types/OpaJourneyTypes.gen";
import runner from "./pages/JourneyRunner";

function journey() {
    QUnit.module("FreightOrdersListListReport journey");

    const defaultTableId = "";

    opaTest("Start application", function (Given: Given, _When: When, Then: Then) {
        Given.iStartMyApp();

        Then.onTheFreightOrdersListGenerated.iSeeThisPage();
    });


    // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
    // opaTest("Perform a global search and check the result", function (Given: Given, When: When, Then: Then) {
    //     When.onTheFreightOrdersListGenerated.onFilterBar().iChangeSearchField("Search Term");
    //     When.onTheFreightOrdersListGenerated.onFilterBar().iExecuteSearch();
    //     Then.onTheFreightOrdersListGenerated.onTable(defaultTableId).iCheckRows();
    //     When.onTheFreightOrdersListGenerated.onFilterBar().iChangeSearchField(undefined);
    //     Then.onTheFreightOrdersListGenerated.onFilterBar().iCheckSearchField(undefined);
    // });


    opaTest("Navigate to ObjectPage", function (_Given: Given, When: When, Then: Then) {
        // Note: this test will fail if the ListReport page doesn't show any data
        When.onTheFreightOrdersListGenerated.onFilterBar().iExecuteSearch();
        Then.onTheFreightOrdersListGenerated.onTable(defaultTableId).iCheckRows();
        When.onTheFreightOrdersListGenerated.onTable(defaultTableId).iPressRow(0);
        Then.onTheFreightOrdersObjectPageGenerated.iSeeThisPage();
    });

    opaTest("Teardown", function (Given: Given) {
        // Cleanup
        Given.iTearDownMyApp();
    });
}

runner.run([journey]);
